language: generic 
sudo: required
services:
  - docker

before_install: 
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true kartiktickoo/react-test npm test -- --coverage

after_success: 
  - docker build -t kartiktickoo/multi-client ./client
  - docker build -t kartiktickoo/multi-nginx ./nginx
  - docker build -t kartiktickoo/multi-server ./server
  - docker build -t kartiktickoo/multi-worker ./worker
